#############################################################################
# Makefile for building: bin/mygps
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue May 27 15:18:40 2014
# Project:  mygps.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile mygps.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc/headers -Isrc/ui/headers -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -lQtCore -lpthread -lgps
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/ .o

####### Files

SOURCES       = src/main/gps-opts.cpp \
		src/main/gps.cpp \
		src/terminal/gps-print.cpp \
		src/terminal/gps-utils.cpp \
		src/ui/gui.cpp \
		src/ui/ui.gps-print.cpp \
		src/ui/ui.gps-utils.cpp \
		src/ui/ui.gps.cpp moc_ui.gps.cpp
OBJECTS       = build/gps-opts.o \
		build/gps.o \
		build/gps-print.o \
		build/gps-utils.o \
		build/gui.o \
		build/ui.gps-print.o \
		build/ui.gps-utils.o \
		build/ui.gps.o \
		build/moc_ui.gps.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		mygps.pro
QMAKE_TARGET  = mygps
DESTDIR       = bin/
TARGET        = bin/mygps

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mygps.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/shared.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile mygps.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/shared.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile mygps.pro

dist: 
	@$(CHK_DIR_EXISTS) build/mygps1.0.0 || $(MKDIR) build/mygps1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/mygps1.0.0/ && $(COPY_FILE) --parents src/headers/dev.gps.h src/headers/gen.gps.h src/ui/headers/ui.gps.h build/mygps1.0.0/ && $(COPY_FILE) --parents src/main/gps-opts.cpp src/main/gps.cpp src/terminal/gps-print.cpp src/terminal/gps-utils.cpp src/ui/gui.cpp src/ui/ui.gps-print.cpp src/ui/ui.gps-utils.cpp src/ui/ui.gps.cpp build/mygps1.0.0/ && (cd `dirname build/mygps1.0.0` && $(TAR) mygps1.0.0.tar mygps1.0.0 && $(COMPRESS) mygps1.0.0.tar) && $(MOVE) `dirname build/mygps1.0.0`/mygps1.0.0.tar.gz . && $(DEL_FILE) -r build/mygps1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) bin/mygps


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ui.gps.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ui.gps.cpp
moc_ui.gps.cpp: src/headers/dev.gps.h \
		src/ui/headers/ui.gps.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) src/ui/headers/ui.gps.h -o moc_ui.gps.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/gps-opts.o: src/main/gps-opts.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gps-opts.o src/main/gps-opts.cpp

build/gps.o: src/main/gps.cpp src/headers/dev.gps.h \
		src/headers/gen.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gps.o src/main/gps.cpp

build/gps-print.o: src/terminal/gps-print.cpp src/headers/dev.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gps-print.o src/terminal/gps-print.cpp

build/gps-utils.o: src/terminal/gps-utils.cpp src/headers/dev.gps.h \
		src/headers/gen.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gps-utils.o src/terminal/gps-utils.cpp

build/gui.o: src/ui/gui.cpp src/ui/headers/ui.gps.h \
		src/headers/dev.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/gui.o src/ui/gui.cpp

build/ui.gps-print.o: src/ui/ui.gps-print.cpp src/ui/headers/ui.gps.h \
		src/headers/dev.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ui.gps-print.o src/ui/ui.gps-print.cpp

build/ui.gps-utils.o: src/ui/ui.gps-utils.cpp src/ui/headers/ui.gps.h \
		src/headers/dev.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ui.gps-utils.o src/ui/ui.gps-utils.cpp

build/ui.gps.o: src/ui/ui.gps.cpp src/ui/headers/ui.gps.h \
		src/headers/dev.gps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ui.gps.o src/ui/ui.gps.cpp

build/moc_ui.gps.o: moc_ui.gps.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_ui.gps.o moc_ui.gps.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

